parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    driver: pdo_mysql
    server_version: 5.7
    db_name: test_database
    db_user: root
    db_pass: ~
    db_port: 3306
    db_collate: utf8mb4_unicode_ci
    db_charset: utf8mb4

doctrine:
    dbal:
        # configure these for your database server
        driver: '%driver%'
        server_version: '%server_version%'
        dbname: '%db_name%'
        user: '%db_user%'
        password: '%db_pass%'
        port: '%db_port%'
        charset: '%db_charset%'
        default_table_options:
            charset: '%db_charset%'
            collate: '%db_collate%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
